export const languageObj = {
  ru: {
    navbarItem: {
      navbarMainLink: 'Главная',
      navbarPartnersLink: 'Партнеры',
      navbarAboutLink: 'Наша компания',
      navbarServicesLink: 'Направления',
      navbarQuestionsLink: 'Консультация',
      navbarPrivacyLink: 'Политика конфиденциальности',
      navbarConditionsLink: 'Условия и положения',
    },
    headerItem: {
      headerMainLink: 'Главная',
      headerPartnersLink: 'Партнеры',
      headerAboutLink: 'Наша компания',
      headerServicesLink: 'Направления',
      headerQuestionsLink: 'Консультация'
    },
    footerItem: {
      menuFooterTitle: 'Меню',
      mainFooterLink: 'Главная',
      partnersFooterLink: 'Партнеры',
      aboutFooterLink: 'Наша компания',
      servicesFooterLink: 'Направления',
      questionsFooterLink: 'Консультация',
      privacyLink: 'Политика конфиденциальности',
      conditionsLink: 'Условия и положения',
      contactsFooterTitle: 'Контакты',
      legalAddress: 'Юридический адрес:',
      legalAddressPlace: '223037, Минская область, Минский район, Колодищанский с/с, 1,1 км западнее д.Жуков Луг, литер А 1-3/к, помещение 10',
      physicalAddress: 'Физический адрес:',
      physicalAddressPlace: 'г.Минск, МКАД 303,<br>БЦ Стратег, оф.315',
      telephone: 'Тел.:<a href="tel:+375175161700" class="footer-link">8(017)516-17-00</a>,<br><a href="tel:+375173551717" class="footer-link">8(017)355-17-17</a>',
      fax: 'Факс: 8(017)516-17-01,<br>8(017)355-17-18',
      postAddress: 'Почтовый адрес:',
      postAddressPlace: '220064, г.Минск, а/я 6',
      emailPost: 'Электронная почта:',
      socialFooterTitle: 'Мы в социальных сетях',
      rights: '© 2010-2024 "Белая крепость". Все права защищены'
    },
    successPopup: {
      successPopupTitle: 'Вопрос успешно отправлен',
      successPopupText: 'Мы скоро свяжемся с Вами...'
    },
    mainPage: {
      introTitle: 'Надежная <span class="infras" data-name="introTitle">IT-инфраструктура</span><br><span>для вашего бизнеса</span>',
      introDesc: 'Выходите на новый уровень с нами<br>Примените правильные и современные цифровые решения и оборудование',
      buttonCall: 'Позвонить',
      buttonWrite: 'Написать нам',
      partnersTitle: 'Партнеры',
      sliderFirstStatus: 'Золотой партнер',
      sliderFirstName: 'Hewlett Packard',
      sliderSecondStatus: 'Золотой партнер',
      sliderSecondName: 'HUAWEI',
      sliderThirdStatus: 'Премьер партнер',
      sliderThirdName: 'CISCO',
      aboutTitle: '&#171; Белая крепость &#187;<br><span>ваш надежный партнер в мире информационных технологий</span>',
      aboutOffer: 'Мы предлагаем комплексные решения для бизнеса любой сложности, от малых предприятий до крупных корпораций',
      whatDoingTitle: 'Что мы делаем:',
      whatDoing1: 'Строим надежную ИТ-инфраструктуру. Создаем единую среду для эффективной работы вашего бизнеса, учитывая текущие и будущие потребности',
      whatDoing2: 'Обеспечиваем бесперебойную работу систем. Круглосуточная поддержка, быстрый ремонт и замена оборудования,регулярное обслуживание',
      whatDoing3: 'Разрабатываем корпоративные сети. Проектируем, устанавливаем и обслуживаем локальные сети, интернет-каналы и беспроводные решения',
      whatDoing4: 'Оптимизируем ИТ-процессы. Проводим аудит, проектируем и внедряем оптимальные решения для вашего бизнеса',
      whatDoing5: 'Внедряем современную IP-телефонию. Обеспечиваем качественную связь с широкими возможностями настройки',
      whatDoing6: 'Осуществляем услуги по внедрению и сопровождению продуктов информационной безопасности (SOAR, SIEM, TIP, DLP, IDS, EDR и тд)',
      whatWeTitle: 'Почему выбирают нас',
      whatWeInfoText1: 'Высокий профессионализм.<br>Сертифицированные инженеры с большим опытом работы',
      whatWeInfoText2: 'Широкий спектр программных инструментов и оборудования от ведущих IT-компаний для интеграции, обмена и обработки данных между бизнес-приложениями, базами данных, сетевыми и веб-сервисами, инфраструктурными компонентами',
      whatWeInfoText3: 'Индивидуальный и комплексный подходы - все услуги из одних рук.<br>Решения под конкретные задачи',
      whatWeInfoText4: 'Надежность.<br>Локальный склад запчастей, круглосуточная поддержка',
      sloganTitle: '&#171; Белая Крепость &#187;<br><span>крепость от информационных угроз</span>',
      sloganSmall: 'Обращайтесь к нам и получите надежное и эффективное решение для вашего бизнеса',
      sloganBig: 'Сделаем ваш бизнес крепче!',
      servicesTitle: 'Направления',
      solutionsName: 'Инфраструктурные решения',
      solutionsSpecific1: '<span></span>Системы хранения данных',
      solutionsSpecific2: '<span></span>Сервера',
      solutionsSpecific3: '<span></span>Гиперконвергентные решения',
      solutionsSpecific4: '<span></span>Системы резервного копирования',
      solutionsSpecific5: '<span></span>Решения на базе облака',
      solutionsText: 'ИТ-инфраструктура предприятия — это единый комплекс программных, технических, коммуникационных, информационных и организационно-технологических средств обеспечения функционирования предприятия, а также средств управления ими.<br>Для обеспечения эффективной деятельности современные предприятия нуждаются в ИТ-инфраструктуре, состоящей из интегрированного комплекса систем, программ и служб. ИТ-инфраструктура должна быть целостной, максимально надежной, грамотно спроектированной, обладать большим запасом прочности, соответствовать не только текущему состоянию бизнеса, но и учитывать его развитие в будущем.<br>Базовая ИТ-инфраструктура является технологической подложкой для работы других слоёв корпоративной архитектуры.',
      defenceName: 'Кибербезопасность',
      defenceSpecific1: '<span></span>Сетевая безопасность',
      defenceSpecific2: '<span></span>Безопасность приложений',
      defenceSpecific3: '<span></span>Безопасность информации или данных',
      defenceText: 'Кибербезопасность - это совокупность технологий, процессов и практик, предназначенных для защиты сетей, устройств, программ и данных от атак, кражи, повреждения, модификации или несанкционированного доступа. Это включает в себя использование специальных программ для проверки на наличие вредоносного программного обеспечения. Соблюдая надлежащую кибербезопасность, вы можете гарантировать, что ваши данные останутся конфиденциальными, а ваш онлайн-опыт безопасным.',
      consultingName: 'IT-консалтинг',
      consultingSpecific1: '<span></span>Аудит',
      consultingSpecific2: '<span></span>Проектирование ИТ инфраструктуры',
      consultingSpecific3: '<span></span>Выбор оптимальной архитектуры',
      consultingText: 'IT-консалтинг — проектно-ориентированная деятельность, связанная с информационной поддержкой бизнес-процессов, позволяющая дать независимую экспертную оценку эффективности использования информационных технологий. Анализ результатов обследования IT-инфраструктуры позволяет устранить ошибки в архитектуре и предложить решение корпоративной IT-системы.',
      supportName: 'Техническая поддержка и сервисное сопровождение',
      supportSpecific1: '<span></span>Служба технической поддержки 24x7',
      supportSpecific2: '<span></span>Сертифицированные инженеры',
      supportSpecific3: '<span></span>Локальный склад запчастей',
      supportText: 'Единый ресурс для решения проблем оборудования, микропрограммного и программного обеспечения, получения запасных деталей и материалов, доступа к обновлениям, а также совместной поддержки для независимых поставщиков ПО.<br>Благодаря мониторингу систем в режиме 24x7, быстрой диагностике, автоматическому созданию заявок и отправке запчастей процесс поддержки становится проще.',
      appName: 'Бизнес-приложения',
      appSpecific1: '<span></span>CRM-системы',
      appSpecific2: '<span></span>Аналитические системы',
      appSpecific3: 'Средства коллективной работы',
      appText: 'Бизнес-приложения — это многофункциональные программные системы и комплексы, предназначенные для автоматизации ключевых бизнес-функций и процессов внутри компании. Наличие таких приложений повышает эффективность ключевых бизнес-процессов предприятия, позволяет сократить сроки поиска и обработки информации, экономить материальные и человеческие ресурсы, а также автоматизировать типовые действия в рамках выполнения процессов и т.д.',
      aiSolutionsName: 'Интеллектуальные инженерные решения',
      aiSolutionsSpecific1: '<span></span>Локальная автоматизация инженерных систем (АСУ)',
      aiSolutionsSpecific2: '<span></span>Система управления энергопотреблением',
      aiSolutionsSpecific3: '<span></span>Система управления инфраструктурой центра обработки данных (ЦОД)',
      aiSolutionsSpecific4: '<span></span>Структурированные системы мониторинга и управления инженерными системами зданий и сооружений (СМИС)',
      aiSolutionsText: 'Автоматизация управления современными зданиями представляет собой комплексную систему аппаратного и программного обеспечения, предназначенную для удаленного централизованного мониторинга и управления инженерными системами. Система управления обеспечивает правильное функционирование и эффективную эксплуатацию современных зданий, отвечая за создание комфорта и безопасности людей, а также служит для оптимизации энергозатрат.',
      ipteleName: 'IP-телефония и видео-конференц-связь',
      ipteleSpecific1: '<span></span>Монтаж',
      ipteleSpecific2: '<span></span>Настройка',
      ipteleSpecific3: '<span></span>Обслуживание',
      ipteleText: 'Быстрая и качественная связь – одно из ключевых технических условий успешного ведения бизнеса. Высокий уровень конкуренции на рынке и глобализация бизнеса предъявляют к связи новые требования: теперь связь должна быть всё более мобильна и предоставлять широкие возможности настроек и переадресаций. Современным решением задачи по настройке качественной доступной связи с максимально широкими возможностями при небольших финансовых издержках выступает IP-телефония.',
      networkName: 'Корпоративные сети',
      networkSpecific1: '<span></span>ЛВС',
      networkSpecific2: '<span></span>Интернет',
      networkSpecific3: '<span></span>WAN каналы передачи данных',
      networkSpecific4: '<span></span>Беспроводные сети',
      networkText: ' Каждая компания при открытии нового офиса или при переезде сталкивается с задачей создания новой IT-инфраструктуры: прокладки и настройки локальной сети, установки и настройки оборудования, настройки сервисов, подключения к внешним сетям связи, дальнейшее техническое обслуживание. Благодаря предложению нашей компании все вопросы, связанные с этой комплексной задачей, можно решить, обратившись к одному интегратору.',
      certificatesTitle: 'Наши сертификаты',
      questionsTitle: 'Мы открыты к обсуждению<br>вашего вопроса',
      questionsSubTitle: 'Оставьте заявку на консультацию<br>и мы перезвоним вам в ближайшее время',
      questionsAddress: 'г.Минск, МКАД 303, БЦ Стратег, оф.315',
      labelConfirm: '<span>Я ознакомлен и принимаю условия <a href="privacy.html" target="_blank">Политики конфиденциальности</a></span>',
      formButton: 'Отправить',
    },
    placeholders: {
      name: 'Введите имя',
      phone: 'Введите телефон',
      email: 'Введите почту',
      message: 'Введите сообщение...'
    },
    partnerPage: {
      partnerAbout: 'О партнере',
      partnerSolutions: 'Решения',
      toPartner: 'К партнеру',
      goBack: 'На главную'
    },
    privacyPage: {
      privacyTitle: 'Политика конфиденциальности',
      privacyTitleText: 'Компания "Белая крепость" стремится обеспечить высокий уровень защиты персональных данных и другой конфиденциальной информации своих клиентов и партнёров. В этой политике конфиденциальности мы подробно описываем принципы и методы обработки и защиты персональных данных, а также меры по обеспечению безопасности информации.',
      personalData: 'Персональные данные',
      personalDataText: 'Персональные данные включают любую информацию, которая прямо или косвенно относится к определённому или определяемому физическому лицу (субъекту персональных данных). Это может быть фамилия, имя, отчество, дата рождения, место жительства, паспортные данные, номера телефонов, адреса электронной почты, фотографии и другая информация, позволяющая идентифицировать личность.',
      principlesTitle: 'Принципы обработки и защиты персональных данных',
      principlesTitleSub: 'Мы обрабатываем и защищаем персональные данные в соответствии со следующими принципами:',
      principlesItem1: '<span>Законность:</span> обработка и защита персональных данных осуществляются только на основании закона и с соблюдением всех правовых норм.',
      principlesItem2: '<span>Ограничение сбора данных:</span> мы собираем только те данные, которые необходимы для выполнения наших обязательств перед клиентами и партнёрами.',
      principlesItem3: '<span>Целенаправленность:</span> мы используем персональные данные исключительно для тех целей, для которых они были предоставлены.',
      principlesItem4: '<span>Точность и актуальность:</span> мы обеспечиваем точность и актуальность предоставленных данных, а также своевременное обновление информации.',
      principlesItem5: '<span>Ограничение доступа:</span> мы предоставляем доступ к персональным данным только тем сотрудникам и партнёрам, которые имеют право работать с ними в соответствии с должностными обязанностями.',
      principlesItem6: '<span>Защита персональных данных:</span> мы принимаем все необходимые меры для защиты персональных данных от несанкционированного доступа, изменения, уничтожения и распространения.',
      measuresTitle: 'Меры по обеспечению безопасности персональных данных',
      measuresTitleSub: 'Для обеспечения безопасности персональных данных мы используем следующие меры:',
      measuresItem1: '<span>Физическая защита:</span> установка надёжных замков, решёток, систем видеонаблюдения и других средств защиты помещений и оборудования.',
      measuresItem2: '<span>Техническая защита:</span> использование антивирусного программного обеспечения, брандмауэров, шифрования данных и других технических средств защиты информации.',
      measuresItem3: '<span>Организационные меры:</span> обучение персонала правилам работы с персональными данными, проведение регулярных проверок и аудита информационной безопасности, а также соблюдение всех внутренних регламентов и процедур.',
      subjectsRightsTitle: 'Права субъектов персональных данных',
      subjectsRightsTitleSub: 'Субъекты персональных данных имеют право на:',
      subjectsRightsItem: '<span>Получение информации о том, какие именно данные обрабатываются и для каких целей.</span><br><span>Доступ к своим данным и возможность их исправления или удаления.</span><br><span> Отзыв согласия на обработку персональных данных.</span><br><span>Защиту своих прав и интересов в случае нарушения правил обработки и защиты персональных данных.</span>',
      responsibilityTitle:'Ответственность за нарушение политики конфиденциальности',
      responsibilityText: 'Нарушение настоящей политики конфиденциальности влечёт за собой ответственность в соответствии с действующим законодательством.',
    },
    conditionsPage: {
      conditionsTitle: 'Условия и положения',
      conditionsConfident: '<span>Конфиденциальность:</span> компания обязуется соблюдать конфиденциальность предоставленной информации и использовать её только в рамках предоставляемых услуг.',
      conditionsServices: '<span>Услуги:</span> компания предоставляет услуги IT-консалтинга, поставки оборудования, разработки корпоративных сетей, IP-телефонии и внедрения продуктов информационной безопасности (SOAR, SIEM, TIP, DLP, IDS, EDR и т. д.).',
      conditionsPricePay: '<span>Цены и оплата:</span> компания предлагает гибкие условия оплаты и прозрачные цены на свои услуги.',
      conditionsSupport: '<span>Гарантии и поддержка:</span> компания гарантирует качество предоставляемых услуг и обеспечивает техническую поддержку своих клиентов на протяжении всего сотрудничества.',
      conditionsCompliance: '<span>Соблюдение законодательства:</span> компания соблюдает все применимые законы и нормы в области информационных технологий и информационной безопасности.',
      conditionsResponsibility: '<span>Ответственность:</span> компания несёт ответственность за сохранность и конфиденциальность предоставленной информации, а также за качество предоставляемых услуг.',
      conditionsDispute: '<span>Разрешение споров:</span> споры между компанией и клиентом решаются путём переговоров или через арбитраж в соответствии с действующим законодательством.',
      conditionsEndContract: '<span>Прекращение договора:</span> договор может быть расторгнут по инициативе одной из сторон при условии соблюдения всех необходимых процедур и выплат, предусмотренных договором.',
      conditionsChangePrivacy: '<span>Изменения в политике конфиденциальности:</span> компания имеет право изменять условия и положения своей политики конфиденциальности, уведомляя об этом своих клиентов заранее.'
    }
  },

  en: {
    navbarItem: {
      navbarMainLink: 'Main',
      navbarPartnersLink: 'Partners',
      navbarAboutLink: 'Our company',
      navbarServicesLink: 'Directions',
      navbarQuestionsLink: 'Consultation',
      navbarPrivacyLink: 'Privacy policy',
      navbarConditionsLink: 'Terms and conditions',
    },
    headerItem: {
      headerMainLink: 'Main',
      headerPartnersLink: 'Partners',
      headerAboutLink: 'Our company',
      headerServicesLink: 'Directions',
      headerQuestionsLink: 'Consultation',
    },
    footerItem: {
      menuFooterTitle: 'Menu',
      mainFooterLink: 'Main',
      partnersFooterLink: 'Partners',
      aboutFooterLink: 'Our company',
      servicesFooterLink: 'Directions',
      questionsFooterLink: 'Consultation',
      privacyLink: 'Privacy policy',
      conditionsLink: 'Terms and conditions',
      contactsFooterTitle: 'Contacts',
      legalAddress: 'Legal address:',
      legalAddressPlace: '223037, Minsk region, Minsk district, Kolodishchansky s/s, 1.1 km west of the village of Zhukov Lug, letter A 1-3/k, room 10',
      physicalAddress: 'Physical address:',
      physicalAddressPlace: 'Minsk, MKAD 303,<br>BC Strateg, office 315',
      telephone: 'Phone:<a href="tel:+375175161700" class="footer-link">8(017)516-17-00</a>,<br><a href="tel:+375173551717" class="footer-link">8(017)355-17-17</a>',
      fax: 'Fax: 8(017)516-17-01,<br>8(017)355-17-18',
      postAddress: 'Post address:',
      postAddressPlace: '220064, Minsk, a/b 6',
      emailPost: 'Email:',
      socialFooterTitle: 'Social networks',
      rights: '© 2010-2024 "White Fortress". All rights reserved'
    },
    successPopup: {
      successPopupTitle: 'Question sent successfully',
      successPopupText: 'We will contact you soon...'
    },
    mainPage: {
      introTitle: 'Reliable <span class="infras" data-name="introTitle">IT infrastructure</span><br><span>for your business</span>',
      introDesc: 'Take it to the next level with us<br>Use the right and modern digital solutions and equipment',
      buttonCall: 'Call',
      buttonWrite: 'Write to us',
      partnersTitle: 'Partners',
      sliderFirstStatus: 'Gold partner',
      sliderFirstName: 'Hewlett Packard',
      sliderSecondStatus: 'Gold partner',
      sliderSecondName: 'HUAWEI',
      sliderThirdStatus: 'Premier partner',
      sliderThirdName: 'CISCO',
      aboutTitle: '&#171;White Fortress&#187;<br><span>your reliable partner in the world of information technology</span>',
      aboutOffer: 'We offer comprehensive solutions for businesses of any complexity, from small businesses to large corporations',
      whatDoingTitle: 'What we do:',
      whatDoing1: 'We build a reliable IT infrastructure. We create a unified environment for the efficient operation of your business, taking into account current and future needs',
      whatDoing2: 'We ensure uninterrupted operation of systems. 24/7 support, fast repair and replacement of equipment, regular maintenance',
      whatDoing3: 'We develop corporate networks. We design, install and maintain local networks, Internet channels and wireless solutions',
      whatDoing4: 'We optimize IT processes. We conduct audits, design and implement optimal solutions for your business',
      whatDoing5: 'We implement modern IP telephony. We provide high-quality communication with wide customization options.',
      whatDoing6: 'We provide services for the implementation and maintenance of information security products (SOAR, SIEM, TIP, DLP, IDS, EDR, etc.)',
      whatWeTitle: 'Why choose us',
      whatWeInfoText1: 'High professionalism.<br>Certified engineers with extensive experience',
      whatWeInfoText2: 'A wide range of software tools and equipment from leading IT companies for integration, exchange and processing of data between business applications, databases, network and web services, infrastructure components',
      whatWeInfoText3: 'Individual and comprehensive approaches - all services from one source.<br>Solutions for specific tasks',
      whatWeInfoText4: 'Reliability.<br>Local spare parts warehouse, 24/7 support',
      sloganTitle: '&#171; White Fortress &#187;<br><span>fortress from information threats</span>',
      sloganSmall: 'Contact us and get a reliable and effective solution for your business',
      sloganBig: 'We will make your business stronger!',
      servicesTitle: 'Directions',
      solutionsName: 'Infrastructure solutions',
      solutionsSpecific1: '<span></span>Data storage systems',
      solutionsSpecific2: '<span></span>Servers',
      solutionsSpecific3: '<span></span>Hyperconverged solutions',
      solutionsSpecific4: '<span></span>Backup systems',
      solutionsSpecific5: '<span></span>Cloud-based solutions',
      solutionsText: 'The IT infrastructure of an enterprise is a single complex of software, technical, communication, information and organizational-technological means of ensuring the functioning of the enterprise, as well as means of managing them.<br>To ensure effective operation, modern enterprises need an IT infrastructure consisting of an integrated set of systems, programs and services. The IT infrastructure must be integral, as reliable as possible, competently designed, have a large margin of safety, correspond not only to the current state of the business, but also take into account its development in the future.<br>The basic IT infrastructure is the technological substrate for the operation of other layers of the corporate architecture.',
      defenceName: 'Cybersecurity',
      defenceSpecific1: '<span></span>Network security',
      defenceSpecific2: '<span></span>Application security',
      defenceSpecific3: '<span></span>Security of information or data',
      defenceText: 'Cybersecurity is a set of technologies, processes, and practices designed to protect networks, devices, programs, and data from attack, theft, damage, modification, or unauthorized access. This includes using special programs to check for malicious software. By practicing proper cybersecurity, you can ensure that your data remains private and your online experience is secure.',
      consultingName: 'IT consulting',
      consultingSpecific1: '<span></span>Audit',
      consultingSpecific2: '<span></span>Design of IT infrastructure',
      consultingSpecific3: '<span></span>Selecting the optimal architecture',
      consultingText: 'IT consulting is a project-oriented activity related to information support of business processes, allowing to give an independent expert assessment of the efficiency of using information technologies. Analysis of the results of the IT infrastructure survey allows to eliminate errors in the architecture and offer a solution for the corporate IT system.',
      supportName: 'Technical support and service support',
      supportSpecific1: '<span></span>Technical support service 24x7',
      supportSpecific2: '<span></span>Certified engineers',
      supportSpecific3: '<span></span>Local warehouse of spare parts',
      supportText: 'A single resource for hardware, firmware and software issues, spare parts and materials, access to updates, and joint support for independent software vendors.<br>With 24x7 system monitoring, rapid diagnostics, automatic ticket creation and parts dispatch, the support process is simplified.',
      appName: 'Business applications',
      appSpecific1: '<span></span>CRM systems',
      appSpecific2: '<span></span>Analytical systems',
      appSpecific3: 'Collaboration tools',
      appText: 'Business applications are multifunctional software systems and complexes designed to automate key business functions and processes within a company. The presence of such applications increases the efficiency of key business processes of an enterprise, allows to reduce the time of searching and processing information, save material and human resources, and automate typical actions within the framework of process execution, etc.',
      aiSolutionsName: 'Intelligent engineering solutions',
      aiSolutionsSpecific1: '<span></span>Local automation of engineering systems (AES)',
      aiSolutionsSpecific2: '<span></span>Energy management system',
      aiSolutionsSpecific3: '<span></span>Data center infrastructure management system',
      aiSolutionsSpecific4: '<span></span>Structured systems for monitoring and controlling engineering systems of buildings and structures (SMIS)',
      aiSolutionsText: 'Automation of modern building management is a complex system of hardware and software designed for remote centralized monitoring and management of engineering systems. The control system ensures the correct functioning and efficient operation of modern buildings, responsible for creating comfort and safety for people, and also serves to optimize energy costs.',
      ipteleName: 'IP telephony and video conferencing',
      ipteleSpecific1: '<span></span>Installation',
      ipteleSpecific2: '<span></span>Setting',
      ipteleSpecific3: '<span></span>Service',
      ipteleText: 'Fast and high-quality communication is one of the key technical conditions for successful business. The high level of competition in the market and the globalization of business impose new requirements on communication: now communication must be increasingly mobile and provide wide possibilities for settings and redirections. IP telephony is a modern solution to the problem of setting up high-quality, accessible communication with the widest possible possibilities at low financial costs.',
      networkName: 'Corporate networks',
      networkSpecific1: '<span></span>LAN',
      networkSpecific2: '<span></span>Internet',
      networkSpecific3: '<span></span>WAN data transmission channels',
      networkSpecific4: '<span></span>Wireless networks',
      networkText: 'Every company, when opening a new office or moving, faces the task of creating a new IT infrastructure: laying and setting up a local network, installing and setting up equipment, setting up services, connecting to external communication networks, and further technical maintenance. Thanks to our company\'s offer, all issues related to this complex task can be resolved by contacting one integrator.',
      certificatesTitle: 'Our certificates',
      questionsTitle: 'We are open to discuss<br>your question',
      questionsSubTitle: 'Leave a request for a consultation<br>and we will call you back shortly',
      questionsAddress: 'Minsk, MKAD 303, Business Center Strateg, office 315',
      labelConfirm: '<span>I have read and accept the terms of the <a href="privacy.html" target="_blank">Privacy Policy</a></span>',
      formButton: 'Submit',
    },
    placeholders: {
      name: 'Enter name',
      phone: 'Enter phone',
      email: 'Enter email',
      message: 'Enter message...'
    },
    partnerPage: {
      partnerAbout: 'Partner',
      partnerSolutions: 'Solutions',
      toPartner: 'To the partner',
      goBack: 'Main'
    },
    privacyPage: {
      privacyTitle: 'Privacy Policy',
      privacyTitleText: 'The White Fortress Company strives to ensure a high level of protection of personal data and other confidential information of its clients and partners. In this privacy policy, we describe in detail the principles and methods of processing and protecting personal data, as well as measures to ensure the security of information.',
      personalData: 'Personal data',
      personalDataText: 'Personal data includes any information that directly or indirectly relates to an identified or identifiable natural person (subject of personal data). This may be a surname, first name, middle name, date of birth, place of residence, passport details, phone numbers, email addresses, photographs and other information that allows you to identify a person.',
      principlesTitle: 'Principles of processing and protecting personal data',
      principlesTitleSub: 'We process and protect personal data in accordance with the following principles:',
      principlesItem1: '<span>Legality:</span> the processing and protection of personal data is carried out only on the basis of the law and in compliance with all legal regulations.',
      principlesItem2: '<span>Limitation of data collection:</span> we collect only the data that is necessary to fulfill our obligations to customers and partners.',
      principlesItem3: '<span>Purposefulness:</span> we use personal data exclusively for the purposes for which they were provided.',
      principlesItem4: '<span>Accuracy and relevance:</span> we ensure the accuracy and relevance provided data, as well as timely updating of information.',
      principlesItem5: '<span>Access restriction:</span> we provide access to personal data only to those employees and partners who have the right to work with them in accordance with their job responsibilities.',
      principlesItem6: '<span>Personal data protection:</span> we take all necessary measures to protect personal data from unauthorized access, modification, destruction and distribution.',
      measuresTitle: 'Measures to ensure the security of personal data',
      measuresTitleSub: 'To ensure the security of personal data, we use the following measures:',
      measuresItem1: '<span>Physical protection:</span> installation of reliable locks, bars, video surveillance systems and other means of protecting premises and equipment.',
      measuresItem2: '<span>Technical protection:</span> use of anti-virus software, firewalls, data encryption and other technical means of information protection.',
      measuresItem3: '<span>Organizational measures:</span> training of personnel in the rules of working with personal data, conducting regular checks and audits of information security, as well as compliance with all internal regulations and procedures.',
      subjectsRightsTitle: 'Rights of personal data subjects',
      subjectsRightsTitleSub: 'Personal data subjects have the right to:',
      subjectsRightsItem: '<span>Obtaining information about what data is processed and for what purposes.</span><br><span>Access to your data and the ability to correct or delete it.</span><br><span>Revocation of consent to the processing of personal data.</span><br><span>Protection of your rights and interests in the event of a violation of the rules for processing and protecting personal data.</span>',
      responsibilityTitle:'Responsibility for violation of the privacy policy',
      responsibilityText: 'Violation of this privacy policy entails liability in accordance with applicable law.',
    },
    conditionsPage: {
      conditionsTitle: 'Terms and Conditions',
      conditionsConfident: '<span>Confidentiality:</span> the company undertakes to maintain the confidentiality of the information provided and use it only within the framework of the services provided.',
      conditionsServices: '<span>Services:</span> the company provides IT consulting services, equipment supply, corporate network development, IP telephony and implementation of information security products (SOAR, SIEM, TIP, DLP, IDS, EDR, etc.).',
      conditionsPricePay: '<span>Prices and payment:</span> the company offers flexible payment terms and transparent prices for its services.',
      conditionsSupport: '<span>Guarantees and support:</span> the company guarantees the quality of the services provided and provides technical support to its clients throughout the entire cooperation.',
      conditionsCompliance: '<span>Compliance with legislation:</span> the company complies with all applicable laws and standards in the field of information technology and information security.',
      conditionsResponsibility: '<span>Responsibility:</span> the company is responsible for the safety and confidentiality of the information provided, as well as for the quality of the services provided.',
      conditionsDispute: '<span>Dispute Resolution:</span> disputes between the company and the client are resolved through negotiations or arbitration in accordance with applicable law.',
      conditionsEndContract: '<span>Termination of the contract:</span> the contract may be terminated by one of the parties, subject to compliance with all necessary procedures and payments stipulated by the contract.',
      conditionsChangePrivacy: '<span>Changes to the privacy policy:</span> the company has the right to change the terms and conditions of its privacy policy, notifying its clients in advance.'
    }
  }
}
